---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-prometheus-main
  namespace: {{ .Values.nSpacemonitor }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/prometheus/prometheus.yml" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-prometheus-rules
  namespace: {{ .Values.nSpacemonitor }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/prometheus/rules/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
