"payout.resultcode": <#if response.getResultCode()??>"${response.getResultCode()}"<#else>null</#if>,
"payout.resultMessage": <#if response.getResultMessage()??>"${response.getResultMessage()}"<#else>null</#if>,
"payout.transactionNumber" : <#if response.getTransactionNumber()??>"${response.getTransactionNumber()}"<#else>null</#if>,
"payout.resellerId" : <#if response.getResellerId()??>"${response.getResellerId()}"<#else>null</#if>,
"payout.resellerName" : <#if response.getResellerName()??>"${response.getResellerName()}"<#else>null</#if>,
"payout.frequency" : <#if response.getPayoutType()??>"${response.getPayoutType()}"<#else>null</#if>,
"payout.payoutType" : <#if response.getPayoutType()??>"${response.getPayoutType()}"<#else>null</#if>,
"payout.stateId" : <#if response.getStateId()??>"${response.getStateId()}"<#else>null</#if>,
"payout.stateName" : <#if response.getStateName()??>"${response.getStateName()}"<#else>null</#if>,
"payout.billingAccountId" : <#if response.getBillingAccountId()??>"${response.getBillingAccountId()}"<#else>null</#if>,
"payout.netPayoutAmount" : <#if response.getNetPayoutAmount()??>"${response.getNetPayoutAmount()}"<#else>null</#if>,
"payout.taxAmount" : <#if response.getTaxAmount()??>"${response.getTaxAmount()}"<#else>null</#if>,
"payout.grossPayoutAmount" : <#if response.getGrossPayoutAmount()??>"${response.getGrossPayoutAmount()}"<#else>null</#if>,
"payout.campaignName" : <#if response.getCampaignName()??>"${response.getCampaignName()}"<#else>null</#if>,
"payout.kpiUid" : <#if response.getKpiUid()??>"${response.getKpiUid()}"<#else>null</#if>,
"payout.paymentChannel" : <#if response.getPaymentChannel()??>"${response.getPaymentChannel()}"<#else>null</#if>,
"payout.createdDate" : <#if response.getCreatedDate()??>"${response.getCreatedDate()}"<#else>null</#if>,
"payout.updatedDate" : <#if response.getUpdatedDate()??>"${response.getUpdatedDate()}"<#else>null</#if>,
"payout.payoutDisbursementDate" : <#if response.getPayoutDisbursementDate()??>"${response.getPayoutDisbursementDate()}"<#else>null</#if>,
"payout.approvalDate" : <#if response.getApprovalDate()??>"${response.getApprovalDate()}"<#else>null</#if>,
"payout.paymentDate" : <#if response.getPaymentDate()??>"${response.getPaymentDate()}"<#else>null</#if>,
"payout.batchId" : null
