#!/bin/bash

mkdir -p /opt/seamless/conf/account-management-service/templates

cp /main/* /opt/seamless/conf/
cp /account-management-main/* /opt/seamless/conf/account-management-service/
cp /account-management-templates/* /opt/seamless/conf/account-management-service/templates/
