#!/bin/bash

mkdir -p /opt/seamless/conf/access-management-system/templates

cp /main/* /opt/seamless/conf/
cp /access-management-main/* /opt/seamless/conf/access-management-system/
cp /access-management-templates/* /opt/seamless/conf/access-management-system/templates/
