#!/bin/bash

mkdir -p /opt/seamless/conf/identity-management/templates

cp /main/* /opt/seamless/conf/
cp /identity-management-main/* /opt/seamless/conf/identity-management/
cp /identity-management-templates/* /opt/seamless/conf/identity-management/templates/

value=`echo ${HOSTNAME_COMMAND} | awk -F'-' '{$NF += 1; printf "%02d\n", $NF}'`

sed -i "s+reference_generator.node_id=01+reference_generator.node_id=${value}+g" /opt/seamless/conf/identity-management/identity-management.properties
sed -i  "s+/var/seamless/log/identity-management+/var/seamless/log/identity-management/idms-${value}+g" /opt/seamless/conf/identity-management/log4j2.xml
