apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-accountlink-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-accountlink-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/accountlinksimulator"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-accountlink-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-accountlink-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountlink
  namespace: {{ .Values.nSpace }}
  labels:
    app: accountlink
spec:
  replicas: {{ .Values.replica.accountlink }}
  selector:
    matchLabels:
      app: accountlink
  template:
    metadata:
      labels:
        app: accountlink
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - accountlink
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: accountlink
        image: {{ .Values.image.accountlink }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-accountlink-main
          mountPath: {{ .Values.conf }}/accountlinksimulator
        - name: vol-logs-accountlink
          mountPath: {{ .Values.logs }}/accountlinksimulator
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-accountlink-main
        configMap:
          name: cm-accountlink-main
      - name: vol-logs-accountlink
        persistentVolumeClaim:
          claimName: logs-accountlink-{{ .Values.nSpace }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accountlink
  name: svc-accountlink
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8091
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30027
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31027
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32027
    {{- end }}
    targetPort: 8091
  selector:
    app: accountlink
  type: NodePort
