---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-agent-assignment-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-agent-assignment-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/agent-assignment-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-agent-assignment-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-agent-assignment-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-assignment
  namespace: {{ .Values.nSpace }}
  labels:
    app: agent-assignment
    version: v1
spec:
  replicas: {{ .Values.replica.agentassignment }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 10%
  selector:
    matchLabels:
      app: agent-assignment
      version: v1
  template:
    metadata:
      labels:
        app: agent-assignment
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - agent-assignment
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
        - name: copy-configs
          image: centos
          command: ['bash','/scripts/configs-copy']
          volumeMounts:
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-cm-main
            mountPath: /main
          - name: vol-cm-agent-assignment-main
            mountPath: /agentassignment-main
          - name: vol-cm-agent-assignment-templates-audit
            mountPath: /agentassignment-audit
          - name: vol-cm-agent-assignment-templates-notification
            mountPath: /agentassignment-notification
          - name: vol-cm-agent-assignment-copy
            mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: agent-assignment
        image: {{ .Values.image.agentassignment }}
        imagePullPolicy: IfNotPresent
#        readinessProbe:
#          tcpSocket:
#            port: 11001
#          initialDelaySeconds: 30
#          periodSeconds: 5
#        livenessProbe:
#          tcpSocket:
#            port: 11001
#          initialDelaySeconds: 30
#          periodSeconds: 20
        ports:
        - containerPort: 11001
        {{- if eq .Values.telemetry_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=agent-assignment -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-agent-assignment
          mountPath: {{ .Values.logs }}/agent-assignment-system
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-agent-assignment-main
        configMap:
          name: cm-agent-assignment-main
      - name: vol-cm-agent-assignment-templates-audit
        configMap:
          name: cm-agent-assignment-templates-audit
      - name: vol-cm-agent-assignment-templates-notification
        configMap:
          name: cm-agent-assignment-templates-notification
      - name: vol-logs-agent-assignment
        persistentVolumeClaim:
          claimName: logs-agent-assignment-{{ .Values.nSpace }}
      - name: vol-cm-agent-assignment-copy
        configMap:
          name: cm-agent-assignment-copy
      - name: config-dir-main
        emptyDir: {}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent-assignment
  name: svc-agent-assignment
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 11001
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30099
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31099
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32099
    {{- end }}
    targetPort: 11001
  selector:
    app: agent-assignment
  type: NodePort
