---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-alertapp-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-alertapp-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/alertapp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-alertapp-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-alertapp-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertapp
  namespace: {{ .Values.nSpace }}
  labels:
    app: alertapp
    version: v1
spec:
  replicas: {{ .Values.replica.alertapp }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: alertapp
      version: v1
  template:
    metadata:
      labels:
        app: alertapp
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - alertapp
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: alertapp
        image: {{ .Values.image.alertapp }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8375
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=alertapp -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:5914 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.ers.alertapp"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-alertapp-main
          mountPath: {{ .Values.conf }}/alertapp
        - name: vol-logs-alertapp
          mountPath: {{ .Values.logs }}/alertapp
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-alertapp-main
        configMap:
          name: cm-alertapp-main
      - name: vol-logs-alertapp
        persistentVolumeClaim:
          claimName: logs-alertapp-{{ .Values.nSpace }}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertapp
  name: svc-alertapp
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8375
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30044
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31044
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32044
    {{- end }}
    targetPort: 8375
  selector:
    app: alertapp
  type: NodePort
