{{- if eq .Values.jar_volume true }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-apmjar-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-apmjar-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/apmjar"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-apmjar-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      type: local
      name: logs-apmjar-{{ .Values.nSpace }}
  storageClassName: manual
{{- end }}
