---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-batch-scheduling-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-batch-scheduling-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/batch-scheduling"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-batch-scheduling-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-batch-scheduling-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-scheduling
  namespace: {{ .Values.nSpace }}
  labels:
    app: batch-scheduling
    version: v1
spec:
  replicas: {{ .Values.replica.batchscheduling }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: batch-scheduling
      version: v1
  template:
    metadata:
      labels:
        app: batch-scheduling
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - batch-scheduling
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-batch-scheduling-main
          mountPath: /batch-scheduling-main
        - name: vol-cm-batch-scheduling-templates
          mountPath: /batch-scheduling-templates
        - name: vol-cm-batch-scheduling-samples
          mountPath: /batch-scheduling-samples
        - name: vol-cm-batch-scheduling-feeder
          mountPath: /batch-scheduling-feeder
        - name: vol-cm-batch-scheduling-notifications
          mountPath: /batch-scheduling-notifications
        - name: vol-cm-batch-scheduling-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: batch-scheduling
        image: {{ .Values.image.batchscheduling }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8085"
          initialDelaySeconds: 50
          periodSeconds: 20
        livenessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8085"
          initialDelaySeconds: 60
          periodSeconds: 40
        ports:
        - containerPort: 8085
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=batch-scheduling-system -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:5914 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.one.batch"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-batch-scheduling
          mountPath: {{ .Values.logs }}/batch-scheduling
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-batch-scheduling-main
        configMap:
          name: cm-batch-scheduling-main
      - name: vol-cm-batch-scheduling-templates
        configMap:
          name: cm-batch-scheduling-templates
      - name: vol-cm-batch-scheduling-feeder
        configMap:
          name: cm-batch-scheduling-feeder
      - name: vol-cm-batch-scheduling-samples
        configMap:
          name: cm-batch-scheduling-samples
      - name: vol-cm-batch-scheduling-notifications
        configMap:
          name: cm-batch-scheduling-notifications
      - name: vol-logs-batch-scheduling
        persistentVolumeClaim:
          claimName: logs-batch-scheduling-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-batch-scheduling-copy
        configMap:
          name: cm-batch-scheduling-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: batch-scheduling
  name: svc-batch-scheduling
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8085
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30088
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31088
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32088
    {{- end }}
    targetPort: 8085
  selector:
    app: batch-scheduling
  type: NodePort
