---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-bi-engine-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-bi-engine-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/bi-engine"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-bi-engine-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-bi-engine-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bi-report-dir-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: bi-report-dir-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/nginx/html/analytics/file"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bi-report-dir-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: bi-report-dir-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-engine
  namespace: {{ .Values.nSpace }}
  labels:
    app: bi-engine
spec:
  replicas: {{ .Values.replica.biengine }}
  selector:
    matchLabels:
      app: bi-engine
  template:
    metadata:
      labels:
        app: bi-engine
    spec:
      nodeName: {{ index (index (include "workerNodes" . | fromYamlArray ) 0).hostnames 0 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - bi-engine
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-biengine-main
          mountPath: /bi-engine-main
        - name: vol-cm-biengine-templates
          mountPath: /bi-engine-templates
        - name: vol-cm-biengine-scripts
          mountPath: /bi-engine-scripts
        - name: vol-cm-biengine-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: bi-engine
        image: {{ .Values.image.biengine }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8917
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=bi-engine -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:5914 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.customer.bi.engine"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: 500m
            memory: 900Mi
          requests:
            cpu: 200m
            memory: 300Mi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-bi-report-dir
          mountPath: /usr/share/nginx/html/analytics/file
        - name: vol-logs-bi-engine
          mountPath: {{ .Values.logs }}/bi-engine
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-biengine-main
        configMap:
          name: cm-biengine-main
      - name: vol-cm-biengine-templates
        configMap:
          name: cm-biengine-templates
      - name: vol-cm-biengine-scripts
        configMap:
          name: cm-biengine-scripts
      - name: vol-logs-bi-engine
        persistentVolumeClaim:
          claimName: logs-bi-engine-{{ .Values.nSpace }}
      - name: vol-bi-report-dir
        persistentVolumeClaim:
          claimName: bi-report-dir-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-biengine-copy
        configMap:
          name: cm-biengine-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bi-engine
  name: svc-bi-engine
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8917
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30017
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31017
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32017
    {{- end }}
    targetPort: 8917
  selector:
    app: bi-engine
  type: NodePort
