apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-config-services-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-config-services-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/config-services"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-config-services-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-config-services-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-services
  namespace: {{ .Values.nSpace }}
  labels:
    app: config-services
spec:
  replicas: {{ .Values.replica.configservices }}
  selector:
    matchLabels:
      app: config-services
  template:
    metadata:
      labels:
        app: config-services
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - config-services
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: config-services
        image: {{ .Values.image.configservices }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9009
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-config-services-main
          mountPath: {{ .Values.conf }}/config-services
        - name: vol-logs-config-services
          mountPath: {{ .Values.logs }}/config-services
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-config-services-main
        configMap:
          name: cm-config-services-main
      - name: vol-logs-config-services
        persistentVolumeClaim:
          claimName: logs-config-services-{{ .Values.nSpace }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-config-services
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 9009
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30039
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31039
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32039
    {{- end }}
    targetPort: 9009
  selector:
    app: config-services
  type: NodePort
