---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-dealer-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-dealer-management-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/dealer-management-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-dealer-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-dealer-management-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-management
  namespace: {{ .Values.nSpace }}
  labels:
    app: dealer-management
spec:
  replicas: {{ .Values.replica.dealermanagement }}
  selector:
    matchLabels:
      app: dealer-management
  template:
    metadata:
      labels:
        app: dealer-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dealer-management
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-dealer-management-main
          mountPath: /dealer-management-main
        - name: vol-cm-dealer-management-templates
          mountPath: /dealer-management-templates
        - name: vol-cm-dealer-management-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: liveness
        image: yauritux/busybox-curl
        command: ['tail','-f','/dev/null']
        livenessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8033"
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: dealer-management
        image: {{ .Values.image.dealermanagement }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 8033
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8033
          initialDelaySeconds: 30
          periodSeconds: 20
        ports:
        - containerPort: 8033
        {{- if eq .Values.apm_client1 true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=dealer-management-system -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=se.seamless.ers"
        {{- end }}
        {{- if eq .Values.telemetry_client1 true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=dealer-management-system -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply1 true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-dealer-management
          mountPath: {{ .Values.logs }}/dealer-management-system
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-dealer-management-main
        configMap:
          name: cm-dealer-management-main
      - name: vol-cm-dealer-management-templates
        configMap:
          name: cm-dealer-management-templates
      - name: vol-logs-dealer-management
        persistentVolumeClaim:
          claimName: logs-dealer-management-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-dealer-management-copy
        configMap:
          name: cm-dealer-management-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dealer-management
  name: svc-dealer-management
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8033
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30003
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31003
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32003
    {{- end }}
    targetPort: 8033
  selector:
    app: dealer-management
  type: NodePort
