---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-identity-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-identity-management-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/identity-management"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-identity-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-identity-management-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-management
  namespace: {{ .Values.nSpace }}
  labels:
    app: identity-management
    version: v1
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replica.identitymanagement }}
  serviceName: "svc-identity-management"
  selector:
    matchLabels:
      app: identity-management
      version: v1
  template:
    metadata:
      labels:
        app: identity-management
        version: v1
    spec:
      nodeName: w1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - identity-management
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        env:
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        volumeMounts:
          - name: config-dir-main
            mountPath: {{ .Values.conf }}
          - name: vol-cm-main
            mountPath: /main
          - name: vol-cm-identity-management-main
            mountPath: /identity-management-main
          - name: vol-cm-identity-management-templates
            mountPath: /identity-management-templates
          - name: vol-cm-identity-management-copy
            mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: identity-management
        image: {{ .Values.image.identitymanagement }}
        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 8219
#        readinessProbe:
#          tcpSocket:
#            port: 8219
#          initialDelaySeconds: 30
#          periodSeconds: 5
#        livenessProbe:
#          tcpSocket:
#            port: 8219
#          initialDelaySeconds: 30
#          periodSeconds: 5
        {{- if eq .Values.telemetry_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=identity-management -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-identity-management
          mountPath: {{ .Values.logs }}/identity-management
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-identity-management-main
        configMap:
          name: cm-identity-management-main
      - name: vol-cm-identity-management-templates
        configMap:
          name: cm-identity-management-templates
      - name: vol-logs-identity-management
        persistentVolumeClaim:
          claimName: logs-identity-management-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-identity-management-copy
        configMap:
          name: cm-identity-management-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-management
  name: svc-identity-management
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8219
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30031
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31031
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32031
    {{- end }}
    targetPort: 8219
  selector:
    app: identity-management
  type: NodePort
