---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-ims-companion-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-ims-companion-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/ims-companion"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-ims-companion-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-ims-companion-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ims-companion
  namespace: {{ .Values.nSpace }}
  labels:
    app:  ims-companion
spec:
  replicas: {{ .Values.replica.imscompanion }}
  selector:
    matchLabels:
      app:  ims-companion
  template:
    metadata:
      labels:
        app:  ims-companion
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ims-companion
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-ims-companion-main
          mountPath: /ims-companion-main
        - name: vol-cm-ims-companion-audit
          mountPath: /ims-companion-audit
        - name: vol-cm-ims-companion-tdr
          mountPath: /ims-companion-tdr
        - name: vol-cm-ims-companion-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: ims-companion
        image: {{ .Values.image.imscompanion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9934
        {{- if eq .Values.telemetry_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=ims-companion -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-ims-companion
          mountPath: {{ .Values.logs }}/ims-companion
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-ims-companion-main
        configMap:
          name: cm-ims-companion-main
      - name: vol-cm-ims-companion-audit
        configMap:
          name: cm-ims-companion-audit
      - name: vol-cm-ims-companion-tdr
        configMap:
          name: cm-ims-companion-tdr
      - name: vol-logs-ims-companion
        persistentVolumeClaim:
          claimName: logs-ims-companion-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-ims-companion-copy
        configMap:
          name: cm-ims-companion-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ims-companion
  name: svc-ims-companion
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 9934
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30019
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31019
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32019
    {{- end }}
    targetPort: 9934
  selector:
    app: ims-companion
  type: NodePort
