---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-integration-services-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-integration-services-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/integration-services"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-integration-services-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-integration-services-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-services
  namespace: {{ .Values.nSpace }}
  labels:
    app: integration-services
    version: v1
spec:
  replicas: {{ .Values.replica.integrationservices }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: integration-services
      version: v1
  template:
    metadata:
      labels:
        app: integration-services
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - integration-services
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-integration-services-main
          mountPath: /integration-services-main
        - name: vol-cm-integration-services-templates
          mountPath: /integration-services-templates
        - name: vol-cm-integration-services-kyc
          mountPath: /integration-services-kyc
        - name: vol-cm-integration-services-surveys
          mountPath: /integration-services-surveys
        - name: vol-cm-integration-services-keys
          mountPath: /integration-services-keys
        - name: vol-cm-integration-services-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: integration-services
        image: {{ .Values.image.integrationservices }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 9007
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9007
          initialDelaySeconds: 30
          periodSeconds: 20
        ports:
        - containerPort: 9007
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-integration-services
          mountPath: {{ .Values.logs }}/integration-services
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-integration-services-main
        configMap:
          name: cm-integration-services-main
      - name: vol-cm-integration-services-templates
        configMap:
          name: cm-integration-services-templates
      - name: vol-cm-integration-services-kyc
        configMap:
          name: cm-integration-services-kyc
      - name: vol-cm-integration-services-surveys
        configMap:
          name: cm-integration-services-surveys
      - name: vol-cm-integration-services-keys
        configMap:
          name: cm-integration-services-keys
      - name: vol-logs-integration-services
        persistentVolumeClaim:
          claimName: logs-integration-services-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-integration-services-copy
        configMap:
          name: cm-integration-services-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration-services
  name: svc-integration-services
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 9007
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30029
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31029
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32029
    {{- end }}
    targetPort: 9007
  selector:
    app: integration-services
  type: NodePort
