---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-ldaplink-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-ldaplink-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/ldaplink-core"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-ldaplink-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-ldaplink-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldaplink
  namespace: {{ .Values.nSpace }}
  labels:
    app: ldaplink
    version: v1
spec:
  replicas: {{ .Values.replica.ldaplink }}
  selector:
    matchLabels:
      app: ldaplink
      version: v1
  template:
    metadata:
      labels:
        app: ldaplink
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ldaplink
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-ldaplink-main
          mountPath: /ldaplink-main
        - name: vol-cm-ldaplink-scripts
          mountPath: /ldaplink-scripts
        - name: vol-cm-ldaplink-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: ldaplink
        image: {{ .Values.image.ldaplink }}
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 8824
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8824
          initialDelaySeconds: 10
          periodSeconds: 20
        ports:
        - containerPort: 8824
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=ldaplink -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=se.seamless.ers.extlink.ldap"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-ldaplink-{{ .Values.nSpace }}
          mountPath: {{ .Values.logs }}/ldaplink-core
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-ldaplink-main
        configMap:
          name: cm-ldaplink-main
      - name: vol-cm-ldaplink-scripts
        configMap:
          name: cm-ldaplink-scripts
      - name: vol-logs-ldaplink-{{ .Values.nSpace }}
        persistentVolumeClaim:
          claimName: logs-ldaplink-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-ldaplink-copy
        configMap:
          name: cm-ldaplink-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldaplink-core
  name: svc-ldaplink
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8824
    targetPort: 8824
  selector:
    app: ldaplink-core
  type: ClusterIP
