---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-link-simulator-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-link-simulator-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/link-simulator"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-link-simulator-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-link-simulator-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-simulator
  namespace: {{ .Values.nSpace }}
  labels:
    app: link-simulator
spec:
  replicas: {{ .Values.replica.linksimulator }}
  selector:
    matchLabels:
      app: link-simulator
  template:
    metadata:
      labels:
        app: link-simulator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - link-simulator
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: link-simulator
        image: {{ .Values.image.linksimulator }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8096
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=link-simulator -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.component.link"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-link-simulator-main
          mountPath: {{ .Values.conf }}/link-simulator
        - name: vol-logs-link-simulator
          mountPath: {{ .Values.logs }}/link-simulator
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-link-simulator-main
        configMap:
          name: cm-link-simulator-main
      - name: vol-logs-link-simulator
        persistentVolumeClaim:
          claimName: logs-link-simulator-{{ .Values.nSpace }}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: link-simulator
  name: svc-link-simulator
  namespace: {{ .Values.nSpace }}
spec:
  ports:
    - name: http
      port: 8096
      {{- if eq .Values.nSpace "ers-dev" }}
      nodePort: 30025
      {{- else if eq .Values.nSpace "ers-staging" }}
      nodePort: 31025
      {{- else if eq .Values.nSpace "ers" }}
      nodePort: 32025
      {{- end }}
      targetPort: 8096
    - name: https
      port: 8095
      {{- if eq .Values.nSpace "ers-dev" }}
      nodePort: 30023
      {{- else if eq .Values.nSpace "ers-staging" }}
      nodePort: 31023
      {{- else if eq .Values.nSpace "ers" }}
      nodePort: 32023
      {{- end }}
      targetPort: 8095
  selector:
    app: link-simulator
  type: NodePort
