---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-notification-manager-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-notification-manager-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/notification-manager"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-notification-manager-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-notification-manager-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager
  namespace: {{ .Values.nSpace }}
  labels:
    app: notification-manager
spec:
  replicas: {{ .Values.replica.notificationmanager }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: notification-manager
  template:
    metadata:
      labels:
        app: notification-manager
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - notification-manager
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-notification-manager-main
          mountPath: /notification-manager-main
        - name: vol-cm-notification-manager-feeder
          mountPath: /notification-manager-feeder
        - name: vol-cm-notification-manager-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: notification-manager
        image: {{ .Values.image.notificationmanager }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8277
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=notification-manager -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.ers.notificationmanager"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - mountPath: {{ .Values.logs }}/notification-manager
          name: vol-logs-notification-manager
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-notification-manager-main
        configMap:
          name: cm-notification-manager-main
      - name: vol-cm-notification-manager-feeder
        configMap:
          name: cm-notification-manager-feeder
      - name: vol-logs-notification-manager
        persistentVolumeClaim:
          claimName: logs-notification-manager-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-notification-manager-copy
        configMap:
          name: cm-notification-manager-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-manager
  name: svc-notification-manager
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8277
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30018
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31018
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32018
    {{- end }}
    targetPort: 8277
  selector:
    app: notification-manager
  type: NodePort
