---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-notification-ui-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name:  logs-notification-ui-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/notification-ui"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-notification-ui-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-notification-ui-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ui
  namespace: {{ .Values.nSpace }}
  labels:
    app: notification-ui
    version: v1
spec:
  replicas: {{ .Values.replica.notificationui }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: notification-ui
      version: v1
  template:
    metadata:
      labels:
        app: notification-ui
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - notification-ui
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: notification-ui
        image: {{ .Values.image.notificationui }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8177
        readinessProbe:
          tcpSocket:
            port: 8177
          initialDelaySeconds: 40
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8177
          initialDelaySeconds: 40
          periodSeconds: 20
          {{- if eq .Values.resourceApply true }}
          resources:
            limits:
              cpu: '1'
              memory: 3Gi
            requests:
              cpu: '0.5'
              memory: 2Gi
          {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-notification-ui-main
          mountPath: {{ .Values.conf }}/notification-ui
        - name: vol-logs-notification-ui
          mountPath: {{ .Values.logs }}/notification-ui
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-notification-ui-main
        configMap:
          name: cm-notification-ui-main
      - name: vol-logs-notification-ui
        persistentVolumeClaim:
          claimName: logs-notification-ui-{{ .Values.nSpace }}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-ui
  name: svc-notification-ui
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8177
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30059
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31059
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32059
    {{- end }}
    targetPort: 8177
  selector:
    app: notification-ui
  type: NodePort
