---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-region-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-region-management-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/region-management-core"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-region-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-region-management-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: region-management
  namespace: {{ .Values.nSpace }}
  labels:
    app: region-management
spec:
  replicas: {{ .Values.replica.regionmanagement }}
  selector:
    matchLabels:
      app: region-management
  template:
    metadata:
      labels:
        app: region-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - region-management
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-region-management-main
          mountPath: /region-management-main
        - name: vol-cm-region-management-templates
          mountPath: /region-management-templates
        - name: vol-cm-region-management-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: region-management
        image: {{ .Values.image.regionmanagement }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=region-management -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=se.seamless.region.management"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-region-management
          mountPath: {{ .Values.logs }}/region-management-core
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-region-management-main
        configMap:
          name: cm-region-management-main
      - name: vol-cm-region-management-templates
        configMap:
          name: cm-region-management-templates
      - name: vol-logs-region-management
        persistentVolumeClaim:
          claimName: logs-region-management-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-region-management-copy
        configMap:
          name: cm-region-management-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: region-management
  name: svc-region-management
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8000
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30008
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31008
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32008
    {{- end }}
    targetPort: 8000
  selector:
    app: region-management
  type: NodePort
