---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-scc-ingestor-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-scc-ingestor-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/scc-live-data-ingestor"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-scc-ingestor-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-scc-ingestor-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-ingestor
  namespace: {{ .Values.nSpace }}
  labels:
    app: scc-ingestor
spec:
  replicas: {{ .Values.replica.sccingestor }}
  selector:
    matchLabels:
      app: scc-ingestor
  template:
    metadata:
      labels:
        app: scc-ingestor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - scc-ingestor
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-scc-ingestor-main
          mountPath: /scc-ingestor-main
        - name: vol-cm-scc-ingestor-scripts
          mountPath: /scc-ingestor-scripts
        - name: vol-cm-scc-ingestor-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: scc-ingestor
        image: {{ .Values.image.sccingestor }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9598
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: " -Xms3000M -Xmx4000M -XX:PermSize=512m -XX:+UseG1GC  -XX:InitiatingHeapOccupancyPercent=70  -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=7 -javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=scc-ingestor -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=se.seamless.scc"
        {{- end }}
	{{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 600Mi
          requests:
            cpu: '0.5'
            memory: 300Mi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-scc-ingestor
          mountPath: {{ .Values.logs }}/scc-live-data-ingestor
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-scc-ingestor-main
        configMap:
          name: cm-scc-ingestor-main
      - name: vol-cm-scc-ingestor-scripts
        configMap:
          name: cm-scc-ingestor-scripts
      - name: vol-logs-scc-ingestor
        persistentVolumeClaim:
          claimName: logs-scc-ingestor-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-scc-ingestor-copy
        configMap:
          name: cm-scc-ingestor-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scc-ingestor
  name: svc-scc-ingestor
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 9598
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30077
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31077
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32077
    {{- end }}
    targetPort: 9598
  selector:
    app: scc-ingestor
  type: NodePort
