---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-scc-payout-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-scc-payout-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/scc-payout-engine"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-scc-payout-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-scc-payout-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-payout
  namespace: {{ .Values.nSpace }}
  labels:
    app: scc-payout
    version: v1
spec:
  replicas: {{ .Values.replica.sccpayout }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: scc-payout
      version: v1
  template:
    metadata:
      labels:
        app: scc-payout
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - scc-payout
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-scc-payout-main
          mountPath: /scc-payout-main
        - name: vol-cm-scc-payout-templates
          mountPath: /scc-payout-templates
        - name: vol-cm-scc-payout-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: scc-payout
        image: {{ .Values.image.sccpayout }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9698
        readinessProbe:
          tcpSocket:
            port: 9698
          initialDelaySeconds: 40
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9698
          initialDelaySeconds: 40
          periodSeconds: 20
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: " -Xms3000M -Xmx4000M -XX:PermSize=512m -XX:+UseG1GC  -XX:InitiatingHeapOccupancyPercent=70  -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=7 -javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=scc-payout -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=se.seamless.scc"
        {{- end }}
	  {{- if eq .Values.resourceApply true }}
          resources:
            limits:
              cpu: '1'
              memory: 3Gi
            requests:
              cpu: '0.5'
              memory: 2Gi
          {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-scc-payout
          mountPath: {{ .Values.logs }}/scc-payout-engine
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-scc-payout-main
        configMap:
          name: cm-scc-payout-main
      - name: vol-cm-scc-payout-templates
        configMap:
          name: cm-scc-payout-templates
      - name: vol-logs-scc-payout
        persistentVolumeClaim:
          claimName: logs-scc-payout-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-scc-payout-copy
        configMap:
          name: cm-scc-payout-copy
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scc-payout
  name: svc-scc-payout
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 9698
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30069
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31069
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32069
    {{- end }}
    targetPort: 9698
  selector:
    app: scc-payout
  type: NodePort
