---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: {{ .Values.nSpace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
data:
  gitrepo: {{ .Values.repo | b64enc }}