---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-subscribersystem-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-subscribersystem-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/subscribersystem"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-subscribersystem-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-subscribersystem-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribersystem
  namespace: {{ .Values.nSpace }}
  labels:
    app: subscribersystem
spec:
  replicas: {{ .Values.replica.subscribersystem }}
  selector:
    matchLabels:
      app: subscribersystem
  template:
    metadata:
      labels:
        app: subscribersystem
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - subscribersystem
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: subscribersystem
        image: {{ .Values.image.subscribersystem }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=subscribersystem -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.ers.extlink.subscriber"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-subscribersystem-main
          mountPath: {{ .Values.conf }}/subscribersystem
        - name: vol-logs-subscribersystem
          mountPath: {{ .Values.logs }}/subscribersystem
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-subscribersystem-main
        configMap:
          name: cm-subscribersystem-main
      - name: vol-logs-subscribersystem
        persistentVolumeClaim:
          claimName: logs-subscribersystem-{{ .Values.nSpace }}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscribersystem
  name: svc-subscribersystem
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8087
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30007
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31007
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32007
    {{- end }}
    targetPort: 8087
  selector:
    app: subscribersystem
  type: NodePort
