---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-template-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-template-management-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/template-management-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-template-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-template-management-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-management
  namespace: {{ .Values.nSpace }}
  labels:
    app: template-management
spec:
  replicas: {{ .Values.replica.templatemanagement }}
  selector:
    matchLabels:
      app: template-management
  template:
    metadata:
      labels:
        app: template-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - template-management
            topologyKey: "kubernetes.io/hostname"

      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: template-management
        image: {{ .Values.image.templatemanagement }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8378
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=template-management-system -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.template"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - mountPath: {{ .Values.conf }}
          name: vol-cm-main
        - mountPath: {{ .Values.conf }}/template-management-system
          name: vol-cm-template-management-main
        - mountPath: {{ .Values.logs }}/template-management-system
          name: vol-logs-template-management
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-template-management-main
        configMap:
          name: cm-template-management-main
      - name: vol-logs-template-management
        persistentVolumeClaim:
          claimName: logs-template-management-{{ .Values.nSpace }}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-management
  name: svc-template-management
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8378
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30040
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31040
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32040
    {{- end }}
    targetPort: 8378
  selector:
    app: template-management
  type: NodePort
