---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-trip-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-trip-management-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/trip-management-system"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-trip-management-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-trip-management-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  trip-management
  namespace: {{ .Values.nSpace }}
  labels:
    app:  trip-management
spec:
  replicas: {{ .Values.replica.tripmanagement }}
  selector:
    matchLabels:
      app:  trip-management
  template:
    metadata:
      labels:
        app:  trip-management
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - trip-management
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-trip-management-main
          mountPath: /trip-management-main
        - name: vol-cm-trip-management-templates
          mountPath: /trip-management-templates
        - name: vol-cm-trip-management-notification
          mountPath: /trip-management-notification
        - name: vol-cm-trip-management-copy
          mountPath: /scripts
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: trip-management
        image: {{ .Values.image.tripmanagement }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12001
        {{- if eq .Values.telemetry_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/apmjar/{{ .Values.telemetry_jar }} -Dotel.service.name=trip-management-system -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://{{ .Values.telemetry_server }}:9411/api/v2/spans -Dotel.logs.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://{{ .Values.telemetry_server }}:4318 -Dotel.javaagent.debug=true -Xmx256m"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1.5'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 1Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-trip-management
          mountPath: {{ .Values.logs }}/trip-management-system
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-trip-management-main
        configMap:
          name: cm-trip-management-main
      - name: vol-cm-trip-management-templates
        configMap:
          name: cm-trip-management-templates
      - name: vol-cm-trip-management-notification
        configMap:
          name: cm-trip-management-notification
      - name: vol-cm-trip-management-copy
        configMap:
          name: cm-trip-management-copy
      - name: vol-logs-trip-management
        persistentVolumeClaim:
          claimName: logs-trip-management-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trip-management
  name: svc-trip-management
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 12001
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30048
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31048
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32048
    {{- end }}
    targetPort: 12001
  selector:
    app: trip-management
  type: NodePort
