---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-txe-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-txe-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/txe"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-txe-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-txe-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: txe
  namespace: {{ .Values.nSpace }}
  labels:
    app: txe
    version: v1
spec:
  podManagementPolicy: Parallel
  serviceName: svc-kyc
  replicas: {{ .Values.replica.txe }}
  selector:
    matchLabels:
      app: txe
      version: v1
  template:
    metadata:
      labels:
        app: txe
        version: v1
    spec:
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - txe
            topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        nameservers:
        - 8.8.8.8
      initContainers:
      - name: copy-configs
        image: centos
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        env:
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: config-dir-mysql
          mountPath: /etc/mysql/conf.d/
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-txe-main
          mountPath: /txe-main
        - name: vol-cm-txe-actions
          mountPath: /txe-actions
        - name: vol-cm-txe-pricing
          mountPath: /txe-pricing
        - name: vol-cm-txe-rules
          mountPath: /txe-rules
        - name: vol-cm-txe-templates
          mountPath: /txe-templates
        - name: vol-data-mysql
          mountPath: /var/lib/mariadb-custom/
        - mountPath: /scripts
          name: vol-cm-txe-copy
      {{- include "hostaliases" . | indent 6 }}
      containers:
      - name: mariadb
        image: {{ .Values.image.mariadb }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_DATABASE
          value: transactionlog
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-mysql
          mountPath: /etc/mysql/conf.d/
        - name: vol-data-mysql
          mountPath: /var/lib/mariadb-custom/
        - name: vol-cm-txe-mysql-schema
          mountPath: /docker-entrypoint-initdb.d
      - name: txe
        image: {{ .Values.image.txe }}
        imagePullPolicy: IfNotPresent
        env:
        - name: HOSTNAME_COMMAND
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
        readinessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 40
        livenessProbe:
          tcpSocket:
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 40
        ports:
        - containerPort: 8777
        - containerPort: 8088
        {{- if eq .Values.apm_client true }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: " -Xms3000M -Xmx4000M -XX:PermSize=512m -XX:+UseG1GC  -XX:InitiatingHeapOccupancyPercent=70  -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0 -XX:ActiveProcessorCount=7 -javaagent:/apmjar/{{ .Values.apm_jar }} -Delastic.apm.service_name=txe -Delastic.apm.server_urls=http://{{ .Values.apm_server }}:8200 -Delastic.apm.secret_token= -Delastic.apm.environment=ers -Delastic.apm.application_packages=com.seamless.ers.txe"
        {{- end }}
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '3'
            memory: 4Gi
          requests:
            cpu: '2'
            memory: 3Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-txe
          mountPath: {{ .Values.logs }}/txe
        {{- if eq .Values.jar_volume true }}
        - name: vol-logs-apmjar
          mountPath: /apmjar
        {{- end }}
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-txe-main
        configMap:
          name: cm-txe-main
      - name: vol-cm-txe-templates
        configMap:
          name: cm-txe-templates
      - name: vol-cm-txe-rules
        configMap:
          name: cm-txe-rules
      - name: vol-cm-txe-actions
        configMap:
          name: cm-txe-actions
      - name: vol-cm-txe-pricing
        configMap:
          name: cm-txe-pricing
      - name: vol-cm-txe-mysql-schema
        configMap:
          name: cm-txe-mysql-schema
      - name: vol-cm-txe-copy
        configMap:
          name: cm-txe-copy
      - name: vol-logs-txe
        persistentVolumeClaim:
          claimName: logs-txe-{{ .Values.nSpace }}
      - name: vol-data-mysql
        persistentVolumeClaim:
          claimName: data-mysql-{{ .Values.nSpace }}
      - name: config-dir-main
        emptyDir: {}
      - name: config-dir-mysql
        emptyDir: {}
      {{- if eq .Values.jar_volume true }}
      - name: vol-logs-apmjar
        persistentVolumeClaim:
          claimName: logs-apmjar-{{ .Values.nSpace }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: txe
  name: svc-txe
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8777
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30021
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31021
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32021
    {{- end }}
    targetPort: 8777
  selector:
    app: txe
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.nSpace }}
  labels:
    app: txe
  name: svc-txe2
spec:
  ports:
  - port: 8088
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30022
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31022
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32022
    {{- end }}
    targetPort: 8088
  selector:
    app: txe
  type: NodePort
