---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-ussdapp-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
  labels:
    type: local
    name: logs-ussdapp-{{ .Values.nSpace }}
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.logs }}/ussdapp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-ussdapp-{{ .Values.nSpace }}
  namespace: {{ .Values.nSpace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: local
      name: logs-ussdapp-{{ .Values.nSpace }}
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ussdapp
  namespace: {{ .Values.nSpace }}
  labels:
    app: ussdapp
spec:
  replicas: {{ .Values.replica.ussdapp }}
  selector:
    matchLabels:
      app: ussdapp
  template:
    metadata:
      labels:
        app: ussdapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ussdapp
            topologyKey: "kubernetes.io/hostname"
      {{- include "hostaliases" . | indent 6 }}
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: ussdapp
        image: {{ .Values.image.ussdapp }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8680
        {{- if eq .Values.resourceApply true }}
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
        {{- end }}
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: vol-cm-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-ussdapp-main
          mountPath: {{ .Values.conf }}/ussdapp
        - name: vol-logs-ussdapp
          mountPath: {{ .Values.logs }}/ussdapp
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timzone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-ussdapp-main
        configMap:
          name: cm-ussdapp-main
      - name: vol-logs-ussdapp
        persistentVolumeClaim:
          claimName: logs-ussdapp-{{ .Values.nSpace }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ussdapp
  name: svc-ussdapp
  namespace: {{ .Values.nSpace }}
spec:
  ports:
  - port: 8680
    {{- if eq .Values.nSpace "ers-dev" }}
    nodePort: 30080
    {{- else if eq .Values.nSpace "ers-staging" }}
    nodePort: 31080
    {{- else if eq .Values.nSpace "ers" }}
    nodePort: 32080
    {{- end }}
    targetPort: 8680
  selector:
    app: ussdapp
  type: NodePort
