---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-billing-settlement-main
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/billing-settlement/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-billing-settlement-feeder
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/billing-settlement/datafeeder/templates/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-billing-settlement-copy
  namespace: {{ .Values.nSpace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-billing-settlement" | quote }}