apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-config-services-main
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/config-services/keystore.pkcs12" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ tpl (.Files.Glob "configs/config-services/main/*").AsConfig . | indent 2 }}