---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-main
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/integration-services/keystore.pkcs12" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ tpl (.Files.Glob "configs/integration-services/main/*").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-templates
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/integration-services/templates/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-kyc
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/integration-services/kyc/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-surveys
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/integration-services/surveys/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-keys
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/integration-services/keys/private-key.pem" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-integration-services-copy
  namespace: {{ .Values.nSpace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-integration-services" | quote }}