---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-ldaplink-main
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/ldaplink-core/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-ldaplink-scripts
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/ldaplink-core/scripts/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-ldaplink-copy
  namespace: {{ .Values.nSpace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-ldaplink-core" | quote }}