---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-link-simulator-main
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/link-simulator/cert.jks" "configs/link-simulator/localhost.crt" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/link-simulator/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}