---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-main
  namespace: {{ .Values.nSpace }}
binaryData:
{{- $files := .Files }}
{{- range tuple "configs/notification-manager/SourceSansPro-Regular.ttf" "configs/notification-manager/taraji.jpeg" "configs/notification-manager/tt.jpeg" }}
  {{ (base .) }}: |-
{{ $files.Get . | b64enc | indent 6 }}
{{- end }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/notification-manager/main/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-feeder
  namespace: {{ .Values.nSpace }}
data:
{{ $currentScope := . }}
{{ range $path, $_ :=  .Files.Glob  "configs/notification-manager/datafeeder/templates/**" }}
{{- with $currentScope}}
  {{ (base $path) }}: |-
{{ .Files.Get $path | indent 6 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-notification-manager-copy
  namespace: {{ .Values.nSpace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-notification-manager" | quote }}
